apiVersion: apps/v1
kind: Deployment
metadata:
  name: conner-wadsworth
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: conner-wadsworth
  template: 
    metadata:
      labels:
        app: conner-wadsworth
    spec:
      containers:
        - name: conner-wadsworth
          image: 'gcr.io/team-project-platform-stcg/teamwebsite:latest'
          ports: 
          - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 250M
            requests:
              cpu: 50m
              memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: connerapp-wadsworth-pod-service
spec:
  selector:
    app: conner-wadsworth
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
---
