apiVersion: apps/v1
kind: Deployment
metadata:
  name: gary-gaines
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: gary-gaines
  template: 
    metadata:
      labels:
        app: gary-gaines
    spec:
      containers:
        - name: gary-gaines
          image: 'gcr.io/team-project-platform-stcg/teamwebsite:latest'
          ports: 
          - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 250M
            requests:
              cpu: 50m
              memory: 100M