apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-kleine
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: sam-kleine
  template:
    metadata:
      labels:
        app: sam-kleine
    spec:
      containers:
      - name: sam-kleine
        image: gcr.io/team-project-platform-stcg/teamwebsite:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M 
---
apiVersion: v1
kind: Service
metadata:
  name: samuelapp-sam-pod-service
spec:
  selector:
    app: sam-kleine
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
---
