apiVersion: apps/v1
kind: Deployment
metadata:
  name: travis-aucoin
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: travis-aucoin
  template: 
    metadata: 
      labels: 
        app: travis-aucoin
    spec: 
      containers: 
      - name: travis-aucoin
        image: gcr.io/team-project-platform-stcg/teamwebsite:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M